<a href="https://colab.research.google.com/github/JanviDharwal/UCS420/blob/main/LabAssignment5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
'''
question 2
 (a)For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
'''
array=np.array([10, 52, 62, 16, 16, 54, 453])
sort=np.sort(array)
print(sort)
#ii. Indices of sorted array
indices=np.argsort(array)
print(indices)
#iii. 4 smallest elements
smol=np.array([10, 52, 62, 16, 16, 54, 453])[:4]
print(smol)
#iv. 5 largest elements
l=np.array([10, 52, 62, 16, 16, 54, 453])[-5:]
print(l)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 52 62 16]
[ 62  16  16  54 453]
