<a href="https://colab.research.google.com/github/JanviDharwal/UCS420/blob/main/LabAssignment4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#question 5
import numpy as np

ucs420_Janvi= np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])

mean_value = np.mean(ucs420_Janvi)
median_value = np.median(ucs420_Janvi)
max_value = np.max(ucs420_Janvi)
min_value = np.min(ucs420_Janvi)
unique_elements = np.unique(ucs420_Janvi)

print("Mean", mean_value)
print("Median", median_value)
print("Max", max_value)
print("Min", min_value)
print("Unique Elements", unique_elements)

reshaped_ucs420_Janvi = ucs420_Janvi.reshape(4, 3)
print("Reshaped Array 4x3\n", reshaped_ucs420_Janvi)

resized_ucs420_Janvi = np.resize(ucs420_Janvi, (2, 3))
print("Resized Array 2x3\n", resized_ucs420_Janvi)


Mean 43.333333333333336
Median 37.5
Max 90
Min 10
Unique Elements [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array 4x3
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array 2x3
 [[10 20 30]
 [40 50 60]]
